### ISSUE TITLE
Add theme

### ISSUE THREAD

**Issue by tapaswenipathak** [tapaswenipathak/Research-Paper-Publications#11]
I have added a [theme](https://github.com/tapaswenipathak/Theme).

- Install using `npm i list-theme`.
- Add the information present in [index.html](https://github.com/tapaswenipathak/Research-Paper-Publications/blob/master/index.html) in the theme's [index.html](https://github.com/tapaswenipathak/Theme/blob/master/index.html#L6-L42) 
- Deploy on a Heroku App.
- Create a PR, add the deployed heroku app link.
- Take the credentials from me.
- Deploy in my Heroku account.

Dep #9, #10.

**Comment by mridubhatnagar** [comment]
I am unable to install theme. It gives the following error.

`npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "i" "list-theme"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 Not found : list-theme
npm ERR! 404 
npm ERR! 404  'list-theme' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mridu/npm-debug.log
`

**Comment by tapaswenipathak** [comment]
`npm install && npm link`.

**Comment by mridubhatnagar** [comment]
> `npm install && npm link`.

npm WARN enoent ENOENT: no such file or directory, open '/home/mridu/package.json'
npm WARN mridu No description
npm WARN mridu No repository field.
npm WARN mridu No README data
npm WARN mridu No license field.
npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "link"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /home/mridu/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/mridu/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/mridu/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mridu/npm-debug.log

**Comment by tapaswenipathak** [comment]
Oh you should have the code in your local, theme repository.  You should run `npm install && npm link` inside the repository.

**Comment by mridubhatnagar** [comment]
> Oh you should have the code in your local, theme repository. You should run `npm install && npm link` inside the repository.

npm WARN Invalid version: "1.0"
npm WARN Theme No description
npm WARN Theme No repository field.
npm WARN Theme No README data
npm WARN Theme No license field.
npm ERR! Linux 4.15.0-43-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "link"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Invalid version: "1.0"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mridu/Theme/npm-debug.log

**Comment by tapaswenipathak** [comment]
Nice, can you just put the code as a theme in the website code? I will see it, great find!

**Comment by mridubhatnagar** [comment]
Do I need to replace the code already present in Themes index.html with research papers index.html?

**Comment by tapaswenipathak** [comment]
> Add the information present in [index.html](https://github.com/tapaswenipathak/Research-Paper-Publications/blob/master/index.html) in the theme's [index.html](https://github.com/tapaswenipathak/Theme/blob/master/index.html#L6-L42)

**Comment by mridubhatnagar** [comment]
Do i need to
1. Clone theme repo inside the research publication repo.
2. Then add index.html in theme's index.html
3. And then do I need to only push index.html for the PR or complete theme's repo?

**Comment by tapaswenipathak** [comment]
Please add the code which would enable the theme on the website and a deployment.

**Comment by tapaswenipathak** [comment]
Feel free if you feel like getting on a call https://calendly.com/tapaswenipathak.

**Comment by mridubhatnagar** [comment]
> Feel free if you feel like getting on a call https://calendly.com/tapaswenipathak.

Scheduled

**Comment by mridubhatnagar** [comment]
I have modified index.html. But, the changes are not getting reflected when I open it in the browser.
